version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: simple_drive_postgres
    restart: always
    environment:
      POSTGRES_USER: simple_drive_user
      POSTGRES_PASSWORD: SimpleDrive2024
      POSTGRES_DB: simple_drive_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: